test:
	pytest -xv --flake8 *.py
	pylint *.py

test_generate_data:
	pytest -xv --flake8 test_generate_data.py
	pylint test_generate_data.py

test_train:
	pytest -xv --flake8 test_train.py
	pylint test_train.py

test_integration:
	pytest -xv --flake8 test_integration.py
	pylint test_integration.py